name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_threshold: "0%"
          config_timezone: Africa/Cairo

      - name: Anime Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-anime.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: AhmedTyson
          plugin_anilist_sections: characters
          plugin_anilist_limit_characters: 22
          config_timezone: Africa/Cairo